package com.quarkbyte.recoveryapp_api.model.enums.csj

enum class InternalStatus {
    CASO_NOVO, EM_RECUPERACAO, FINALIZADO, NAO_RECUPERADO, NEGOCIANDO, PAGO, RECUPERADO, RECUPERADO_USUARIO, REPARADO_FRANQUIA, ACOMPANHAR, SEM_ACORDO, SENDO_PROCESSADO, TROCADO_GARANTIA
}